project:
  type: website

website:
  title: 'AIRA'
  site-url: https://ai-riksarkivet.github.io
  favicon: assets/riks.png
  repo-url: https://github.com/AI-Riksarkivet/blog.github.io
  repo-actions: [source, issue]
  repo-link-target: _blank
  navbar:
    logo: assets/riks.png
    right:
      - text: Models & Datasets
        href: https://huggingface.co/Riksarkivet
      - text: Tools
        menu:
          - text: MCPs
            href: https://github.com/AI-Riksarkivet/oxenstierna
          - text: HTRflow-APP
            href: https://github.com/AI-Riksarkivet/htrflow_app
          - text: HTRflow
            href: https://github.com/AI-Riksarkivet/htrflow
      - text: Publications
        menu:
          - text: SWENER-1800
            href: https://journals.uio.no/dhnbpub/article/view/11489
      - about.qmd
      - cite.qmd
    tools:
      - icon: github
        href: https://github.com/AI-Riksarkivet
      - icon: rss
        href: index.xml


format:
  html:
    theme: cosmo #theme.scss
    css: styles.css
